name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this support request.
  - type: checkboxes
    id: terms
    attributes:
      label: Required Reading
      description: "- I have read the [README](../blob/master/README.md) and [Debugging](../blob/master/README.md#debugging-1) section\n- I am aware of the [API Documentation](../blob/master/README.md#api-documentation)\n- I am aware of the [CHANGELOG](../blob/master/CHANGELOG.md)"
      options:
        - label: Confirmed
          required: true
  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: What version of our software are you running?
      placeholder: "Consult your package.json (do not enter 'latest')"
    validations:
      required: true
  - type: textarea
    id: doctor
    attributes:
      label: Cordova platform
      description: "Execute `$ cordova platform` and provide the output here."
      placeholder: "$ cordova platform"
      render: shell
    validations:
      required: true
  - type: textarea
    id: plugins
    attributes:
      label: Cordova plugins
      description: "Execute `$ cordova plugins` and provide the output here."
      placeholder: "$ cordova plugins"
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: os
    attributes:
      label: Mobile operating-system(s)
      description: Which mobile operating-system(s) is this issue reported upon?
      options:
        - label: iOS
        - label: Android
  - type: input
    id: device-info
    attributes:
      label: Device Manufacturer(s) and Model(s)
      description: What is the device model(s) and manufacturer(s)
      placeholder: eg Google Pixel 6, iPhone 13 Pro
    validations:
      required: true
  - type: input
    id: device-os
    attributes:
      label: Device operating-systems(s)
      description: Affected device operating system
      placeholder: eg iOS 18.1, Android 13
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what happened and what did you expect to happen.
    validations:
      required: true  
  - type: textarea
    id: config
    attributes:
      label: Plugin Code and/or Config
      description: Provide the Config you're using with the `BackgroundFetch.configure(config)` method along with any other relevant code.
      placeholder: "Paste your Config or code here, eg: BackgroundFetch.configure(config).\n\nYour code will be automatically syntax-highlighted"
      render: typescript
    validations:
      required: true  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: "include iOS / Android logs\n- $ adb logcat -s TSBackgroundFetch:V\n- ios XCode logs\n- Logs from BackgroundGeolocation.emailLog(address)"
      render: shell

